"""0002_ai_job_item_columns

Revision ID: 5a93ad6a8f7c
Revises: 05669733cef1
Create Date: 2026-05-04 07:39:06.118062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a93ad6a8f7c'
down_revision: Union[str, None] = '05669733cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.SmallInteger(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_ai_analysis_jobs_item_id'), ['item_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_jobs_item_id', 'items', ['item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_result_raw', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('ai_result_raw')
        batch_op.drop_column('ai_error')

    with op.batch_alter_table('ai_analysis_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_jobs_item_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_analysis_jobs_item_id'))
        batch_op.drop_column('retry_count')
        batch_op.drop_column('started_at')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
